### ISSUE TITLE
Measure and expose shipper queue performance metrics

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#11]
Add metrics counters and gauges for the follow set of metrics, and ensure they are exposed on the shipper's HTTP monitoring interface under /debug/vars:

- [ ] Report the following set of queue metrics:
  - [ ] The current configured maximum size of the queue:
    - [x] Report the maximum queue size in events for the memory queue: https://github.com/elastic/elastic-agent-shipper/blob/e231e51569184216ad660079cec8ee5082c22ae8/monitoring/queuemon.go#L131
    - [x] Report the maximum queue size in bytes for the disk queue.
  - [ ] The current utilization of the queue in events:
    - [x] Report the current utilization of the queue in events for the memory queue: https://github.com/elastic/elastic-agent-shipper/blob/e231e51569184216ad660079cec8ee5082c22ae8/monitoring/queuemon.go#L130
    - [x] Report the current utilization of the queue in bytes for the disk queue.
  - [ ] https://github.com/elastic/elastic-agent-shipper/issues/145

The eventual goal is to expose these metrics on the agent details page (example `https://$kbana/app/fleet/agents/$agentID`) in fleet via the agent monitoring metrics.

**Comment by ph** [comment]
@michel-laterman Would be good to have your inputs here too

**Comment by michel-laterman** [comment]
As far as diagnostics go, we would like to be able to access recent metrics/tracing data in order to include them with our bundles.

If metrics/tracing are handled through the pipeline env then we can use a queue or buffer of some sort to capture recent data (similar to the ring-buffer)

**Comment by fearful-symmetry** [comment]
Okay, so I'm just gonna use this to track the various intersecting issues needed for queue metrics:

- [ ] merge the actual PR that defines the metrics: https://github.com/elastic/beats/pull/31289 
- [ ] Implement the "basic" queue size and max size metrics in the queue
- [ ] Implement the "oldest event" metric in the queue(s)
- [ ] Implement queue lag, once this is dealt with: https://github.com/elastic/beats/issues/31307
- [ ] Implement the basic metrics reporter in the shipper, including the derived metrics based on what metrics are available from the queue

**Comment by cmacknz** [comment]
I am moving the output metrics to a separate issue, let's just focus on the queue metrics with this issue.

**Comment by cmacknz** [comment]
https://github.com/elastic/elastic-agent-shipper/issues/153

**Comment by leehinman** [comment]
Tried to think of things that would be useful for the disk queue, here is what I came up with.

- Size on Disk (queue already tracks this)
- Number of Events (need to add code to track)
- Rate of Events added to queue last 1, 5, 15 minutes
- Rate of Events removed from queue last 1, 5, 15 minutes
- Date of oldest segment (once a segment is full, we shouldn't write to it again, so this should show us how tail of queue is doing and if we have at least one stuck event)

**Comment by fearful-symmetry** [comment]
Looks like it got auto-closed. Since this is a meta-issue, reopening for now...

**Comment by nimarezainia** [comment]
> * Date of oldest segment (once a segment is full, we shouldn't write to it again, so this should show us how tail of queue is doing and if we have at least one stuck event)

@leehinman what happens when an event is "stuck"? does it block?

**Comment by leehinman** [comment]
> @leehinman what happens when an event is "stuck"? does it block?

This only happens if you have enabled infinite retries.  But in that case an event that can't be delivered will be re-tried over and over again.  So it will take up space in the queue, but other events will still be delivered.  If you get enough events that can't be delivered then the queue will fill up.  That would block reading of new events.  This is expected behavior with infinite retries.

**Comment by nimarezainia** [comment]
> > @leehinman what happens when an event is "stuck"? does it block?
> 
> This only happens if you have enabled infinite retries. But in that case an event that can't be delivered will be re-tried over and over again. So it will take up space in the queue, but other events will still be delivered. If you get enough events that can't be delivered then the queue will fill up. That would block reading of new events. This is expected behavior with infinite retries.


Not sure if this is an issue we need to deal with right now but Could we have a retry queue for events that have reached some retry threshold. Yank them out of the main queue and use a separate thread to retry.

**Comment by leehinman** [comment]
> Not sure if this is an issue we need to deal with right now but Could we have a retry queue for events that have reached some retry threshold. Yank them out of the main queue and use a separate thread to retry.

Lots of ways to address this.  I'm thinking we wait a bit to see what happens with the queues from a performance perspective and then we can work on retries & failure states.

**Comment by cmacknz** [comment]
Closing, creating a new issue with the metrics that will be in the redesigned health dashboard.
