### ISSUE TITLE
[Meta] disk queue journey to GA

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent-shipper#118]
## Checklist to achieve `experimental` status

- [ ] Add disk queue configuration to shipper configuration
- [ ] Add option to supply encryption key in configuration
- [ ] Add code to request key from elastic-agent in managed mode
- [ ] Add disk queue options/operation to documentation

## Checklist to achieve `beta` status

- [ ] Fleet UI, Add option to enable disk queue and send down configuration
- [ ] Verify keystore is maintained during agent upgrades
- [ ] Build Tool to performance test shipper with & without disk queue
- [ ] Add Disk queue metrics (memory, cpu, disk usage) to shipper metrics

## Checklist to achieve `ga` status

- [ ] Fleet UI, Add feature so integrations can require disk queue
- [ ] Fleet UI, Update agent dashboard visualization with queue metrics

**Comment by mbudge** [comment]
Wouldn't it be more efficient to use in-memory queues which temporarily fall back to on-disk queues if there's a network issue?

When the connectivity issue is resolved, push the events from the on-disk queue back to the output integration. I've built software which did this using channels in Go to add redundancy by caching data to disk. This was done when there was a problem writing to elastic using the go-elasticsearch bulk indexer and it worked well. The software would periodically check connectivity to the cluster and send the events when there was no longer an issue.

This could be done by having an option to flush the in-memory queue to the on-disk queue instead of dropping the events. This would reduce the resources required to run on-disk queues on busy production servers 24/7. It sounds like on disk queues on busy domain controllers or other critical systems might use more resource which could trigger out IT teams to complain. It's too complicated to have separate policies in large multi-regional deployments to have in-memory queues on a subset of endpoints.

**Comment by cmacknz** [comment]
It's a good idea, but exploring that needs to come after making the disk queue available at all. Today there is definitely a performance penalty to write to disk as it requires serializing the event twice (once to disk, once to the output) but we haven't thoroughly quantified what it is. We may also be able to improve that cost.
