### ISSUE TITLE
[Meta][Project] Shipper phase 2: Migrate Endpoint Security and the security beats to the shipper

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#16]
Phase 2 is where integration testing with the endpoint security solution and the security beats begins. The feature set from phase 1 can be used as a starting point for this integration. 

Development to support the disk queue in the agent and shipper will begin in this phase, along with the work to migrate processing to the shipper. These new features are not strict requirements for releasing support for the security inputs.

## Dependencies
To support the phase 2 shipper the control plane must:
- [ ] The agent policy's input processor configurations must be provided to the shipper.

## Implementation
- [ ] Perform integration and compatibility testing of the shipper, endpoint security, and security beats.
- [ ] Support the disk queue.
  - [ ] Immediately acknowledge events persisted to the disk queue when an input is subscribed to the acknowledgement stream. 
  - [ ] https://github.com/elastic/beats/issues/30069
  - [ ] Investigate changing the disk queue serialization format to match that of the output
- [ ] Support encrypted disk queues (either in inputs like endpoint security or within the shipper itself).
- [ ] Implement processing in the shipper binary:
  - [ ] Add a processor section to shipper configuration file that is compatible with the processor configurations in existing agent policies
  - [ ] Apply the correct processors to each published event based on the configured global, input, or data stream specific processors that were configured.
  - [ ] Annotate events that encountered processor errors with the ECS [event.kind: pipeline_error](https://www.elastic.co/guide/en/ecs/current/ecs-event.html#field-event-kind) and add an [error.message](https://www.elastic.co/guide/en/ecs/current/ecs-error.html#field-error-message) with the cause. 
  - [ ] Collect and return detected processor errors in the publish RPC response.
  - [ ] Incorporate processing into the existing integration tests.
  - [ ] Allow global processors: https://github.com/elastic/beats/issues/29459
    - [ ] Decide how global processors will be configured, per agent policy, per output, etc.
- [ ] Instrument the shipper with distributed tracing:
  - [ ] Propagate traces through each stage of the processing pipeline, and to the output in the format appropriate for the transport (e.g. HTTP).
  - [ ] Allow enabling or disabling tracing based on configuration. Ideally allow configuring the degree of sampling applied.
- [ ] https://github.com/elastic/beats/issues/29778

## QA / Testing Needs
TBD

## Documentation
TBD

## Target

- Definition / Design: 8.3
- Beta: TBD
- GA: TBD

**Comment by softengchick** [comment]
Brian McKinney and Michelle Bennett will be working this for Endpoint.

**Comment by cmacknz** [comment]
@softengchick @brian-mckinney is there an issue for this on the endpoint side we can follow?

If you have not seen it recently, the gRPC API for the shipper is defined at https://github.com/elastic/elastic-agent-shipper-client/tree/main/api. The current API is meant to be generic but it is tailored to the needs of Beats since that is what we started with. It is possible we missed something that could make integrating with Endpoint easier.

Reach out once you are ready to start work with any questions you have. I expect this will be a larger change for Endpoint than the move to the V2 control protocol since it isn't just iterating on something Endpoint already supports.
