### ISSUE TITLE
Meta Issue: Shipper configuration and I/O

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent-shipper#226]
This is a meta-issue for tracking changes, bugs, or discussions related to the shipper's config and how it communicates with other components:

- [ ] https://github.com/elastic/elastic-agent/issues/1729 
- [ ] https://github.com/elastic/elastic-agent/issues/1744 
- [ ] https://github.com/elastic/elastic-agent-shipper/issues/224
- [ ] https://github.com/elastic/elastic-agent-shipper/issues/225
