### ISSUE TITLE
[Meta][Project] Implement the Elastic Agent Data Shipper

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent-shipper#3]
## Goal
The is the project issue tracking the implementation of the Elastic agent data shipper, as designed in the [proposal](https://docs.google.com/document/d/1NaaoweevnylnGAPXzuwvwuFcC7dYSIDNUoBkf2SCR5I/edit?usp=sharing).

![image](https://user-images.githubusercontent.com/3466215/158591822-96360185-5cf7-479b-89ea-f072637e1089.png)

## Motivation
The shipper is part of the Elastic Agent v2 project: https://github.com/elastic/elastic-agent/issues/189

The goals of the Elastic agent data shipper are to:

- Remove the need for processing, queueing, and output protocols to be reimplemented in each input.
- Minimize the number of output connections required in Elastic agent deployments.
- Simplify configuration and performance tuning of Elastic agent output pipelines.
- Make Elastic agent output pipelines more observable and easier to debug.
- Define the event publishing interface all Elastic agent inputs will use.
- Improve on or maintain the performance of the existing beats outputs.

## Development Plan
The rollout of the shipper to customers will occur in incremental phases:

- [ ] https://github.com/elastic/elastic-agent-shipper/issues/15
- [ ] https://github.com/elastic/elastic-agent-shipper/issues/16
- [ ] **Phase 3**: Migrate remaining beats and agent inputs. TBD.

**Comment by cmacknz** [comment]
Closing, moving to meta issues that are aligned with the release cycle for tracking.
