### ISSUE TITLE
[Meta][Feature] Implement encrypted disk queue

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent-shipper#33]
# Summary

This is a feature meta issue to implement the encrypted disk queue for the shipper. The scope is restricted to implementation of encryption for the existing beats disk queue, changing how the queue interacts with producers, consumers and pipelines is out of scope.  Design doc can be found [here.](https://docs.google.com/document/d/1l96-0IY18uJHZsItnFpniFRo9156GyKqz6VzKtysG1A/edit)

# Milestones

This feature is considered complete when the following conditions are met:

- [ ] benchmark existing beats disk queue
- [ ] Implement encrypted queue in beats repo
- [ ] Add end to end test that exercises encrypted queue in beats repo
- [ ] Add to shipper binary
  - [ ] https://github.com/elastic/elastic-agent-shipper/issues/41 
  - [ ] Obtain and store the encryption key: https://github.com/elastic/elastic-agent/issues/582
- [ ] benchmark encrypted disk queue

# Related Issues
- elastic/obs-dc-team#729

**Comment by cmacknz** [comment]
A few questions as I'm working on making sure we have all the pieces we need for this tracked somewhere:

>  Implement encrypted queue in beats repo

The encryption will be disabled by default in beats, correct? Likely an undocumented configuration file parameter or similar? I don't think we want to support the encrypted queue for beats (at least initially), and I don't think there's a suitable key store to use there. 

> Add to shipper binary

This is where integration with the key storage would happen, which depends on https://github.com/elastic/elastic-agent/pull/398 right? How are we planning to integrate with this? Do we need an issue created for the agent to expose this as part of the control protocol?

>  Add end to end test that exercises encrypted queue in beats repo

It could also make sense to do the end to end test of encrypted queue from the shipper binary rather than beats, but it depends on what you are thinking for testing.

**Comment by cmacknz** [comment]
Added https://github.com/elastic/elastic-agent-shipper/issues/41 as a dependency of this work if it isn't completed by the time we try to integrate this into the shipper.

**Comment by zez3** [comment]
Would the encryption overhead not slow/bog down the ingest queue rate?
I guess some benchmarks will show the difference.

I think that if someone already has access on your host where your Agent is running you would have to worry about other more important stuff first.

Unless there's a TPM/HSM in place, from my point of view as a security engineer the expected protection that DPAPI CryptProtectData is supposed to offer is not really there. As soon as the encryption("private") key or seed has reached the memory that is an easy job for a malicious actor to extract it. More easy on VMs or containers. On windows Systems the use of CRYPTPROTECT_LOCAL_MACHINE allows any user to decrypt it. You don't even need to do memory dumps. 
https://docs.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata#remarks

`When CRYPTPROTECT_LOCAL_MACHINE flag is set, it associates the data encrypted with the current computer instead of with an individual user. Any user on the computer on which CryptProtectData is called can use CryptUnprotectData to decrypt the data.
" `
Window 11 tries to force the TPM use nowadays.

Some might say it's better than nothing others might say it's better without it.
I think that it's good to have it on the Agent configuration encryption but not necessarily on the queue

Just my 2 cents

**Comment by cmacknz** [comment]
@zez3 encrypting the queue will be optional, for many of the reasons you've listed.

**Comment by leehinman** [comment]
Closing in favor of #118
